"""add_source_app_name_and_package_fields

Revision ID: 8b5f77ebacc2
Revises: 682db436b290
Create Date: 2026-01-09 18:45:50.099719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b5f77ebacc2'
down_revision: Union[str, None] = '682db436b290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_preferences_user_id', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index('idx_search_history_created_at', table_name='search_history')
    op.drop_index('idx_search_history_user_id', table_name='search_history')
    op.drop_table('search_history')
    op.add_column('content_items', sa.Column('source_app_name', sa.String(length=100), nullable=True))
    op.add_column('content_items', sa.Column('source_app_package', sa.String(length=200), nullable=True))
    # Note: key_takeaways is already JSONB in the model, so no conversion needed
    # Commenting out the problematic alter_column that tries to convert JSONB to ARRAY
    # op.alter_column('content_items', 'key_takeaways',
    #            existing_type=postgresql.JSONB(astext_type=sa.Text()),
    #            type_=sa.ARRAY(sa.Text()),
    #            existing_nullable=True)
    op.alter_column('content_items', 'ingestion_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('content_items', 'ai_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('content_items', 'processing_status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='processingstatus'),
               nullable=True,
               existing_server_default=sa.text("'pending'::processingstatus"))
    op.drop_index('idx_content_items_user_category_id', table_name='content_items')
    op.create_index(op.f('ix_content_items_user_category_id'), 'content_items', ['user_category_id'], unique=False)
    # Use raw SQL with IF EXISTS to handle cases where constraint doesn't exist
    op.execute("ALTER TABLE magic_link_tokens DROP CONSTRAINT IF EXISTS uq_magic_link_tokens_token")
    op.execute("DROP INDEX IF EXISTS ix_magic_link_tokens_token")
    op.create_index(op.f('ix_magic_link_tokens_token'), 'magic_link_tokens', ['token'], unique=True)
    op.drop_index('idx_notification_history_content', table_name='notification_history')
    op.drop_index('idx_notification_history_user_date', table_name='notification_history')
    op.drop_index('unique_daily_notification', table_name='notification_history')
    op.create_index(op.f('ix_notification_history_content_item_id'), 'notification_history', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_notification_history_id'), 'notification_history', ['id'], unique=False)
    op.create_index(op.f('ix_notification_history_user_id'), 'notification_history', ['user_id'], unique=False)
    op.drop_index('idx_space_content_added_at', table_name='space_content')
    op.drop_index('idx_space_content_content_id', table_name='space_content')
    op.drop_index('idx_space_content_space_id', table_name='space_content')
    op.drop_constraint('uq_space_content', 'space_content', type_='unique')
    op.create_index(op.f('ix_space_content_added_at'), 'space_content', ['added_at'], unique=False)
    op.create_index(op.f('ix_space_content_content_id'), 'space_content', ['content_id'], unique=False)
    op.create_index(op.f('ix_space_content_space_id'), 'space_content', ['space_id'], unique=False)
    op.drop_index('idx_space_invitations_email', table_name='space_invitations')
    op.drop_index('idx_space_invitations_space_id', table_name='space_invitations')
    op.drop_index('idx_space_invitations_token', table_name='space_invitations')
    op.drop_constraint('space_invitations_token_key', 'space_invitations', type_='unique')
    op.drop_constraint('uq_space_invitation_email', 'space_invitations', type_='unique')
    op.create_index(op.f('ix_space_invitations_email'), 'space_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_space_invitations_space_id'), 'space_invitations', ['space_id'], unique=False)
    op.create_index(op.f('ix_space_invitations_token'), 'space_invitations', ['token'], unique=True)
    op.drop_index('idx_space_members_role', table_name='space_members')
    op.drop_index('idx_space_members_space_id', table_name='space_members')
    op.drop_index('idx_space_members_user_id', table_name='space_members')
    op.drop_constraint('uq_space_user', 'space_members', type_='unique')
    op.create_index(op.f('ix_space_members_role'), 'space_members', ['role'], unique=False)
    op.create_index(op.f('ix_space_members_space_id'), 'space_members', ['space_id'], unique=False)
    op.create_index(op.f('ix_space_members_user_id'), 'space_members', ['user_id'], unique=False)
    op.alter_column('spaces', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_spaces_ai_ready', table_name='spaces')
    op.drop_index('idx_spaces_created_by', table_name='spaces')
    op.drop_index('idx_spaces_invite_token', table_name='spaces')
    op.drop_index('idx_spaces_is_active', table_name='spaces')
    op.drop_index('idx_spaces_is_pinned', table_name='spaces')
    op.drop_index('idx_spaces_is_public', table_name='spaces')
    op.drop_constraint('spaces_invite_token_key', 'spaces', type_='unique')
    op.create_index(op.f('ix_spaces_created_by'), 'spaces', ['created_by'], unique=False)
    op.create_index(op.f('ix_spaces_invite_token'), 'spaces', ['invite_token'], unique=True)
    op.create_index(op.f('ix_spaces_is_active'), 'spaces', ['is_active'], unique=False)
    op.drop_column('spaces', 'is_public')
    op.drop_column('spaces', 'is_pinned')
    op.drop_column('spaces', 'member_count')
    op.drop_column('spaces', 'ai_ready')
    op.alter_column('user_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_user_categories_user_id', table_name='user_categories')
    op.create_index(op.f('ix_user_categories_user_id'), 'user_categories', ['user_id'], unique=False)
    op.drop_index('idx_user_devices_stale', table_name='user_devices', postgresql_where='(is_active = true)')
    op.drop_index('idx_user_devices_token', table_name='user_devices', postgresql_where='(is_active = true)')
    op.drop_index('idx_user_devices_user_id', table_name='user_devices')
    op.create_index(op.f('ix_user_devices_id'), 'user_devices', ['id'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.drop_index('idx_notification_settings_enabled_time', table_name='user_notification_settings', postgresql_where='(is_enabled = true)')
    op.drop_index('idx_notification_settings_user_id', table_name='user_notification_settings')
    op.drop_constraint('user_notification_settings_user_id_key', 'user_notification_settings', type_='unique')
    op.create_index(op.f('ix_user_notification_settings_id'), 'user_notification_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_notification_settings_user_id'), 'user_notification_settings', ['user_id'], unique=True)
    # Use raw SQL with IF EXISTS to handle cases where index/constraints don't exist
    op.execute("DROP INDEX IF EXISTS ix_users_supabase_id")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_users_supabase_id")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_username_key")
    # Drop columns safely with IF EXISTS
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS username")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS plan")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS supabase_id")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS monthly_limit")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS ai_summaries_used")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_summaries_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('monthly_limit', sa.INTEGER(), server_default=sa.text('500'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('supabase_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('plan', sa.VARCHAR(length=20), server_default=sa.text("'free'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_username_key', 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('uq_users_supabase_id', 'users', ['supabase_id'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_users_supabase_id', 'users', ['supabase_id'], unique=False)
    op.drop_index(op.f('ix_user_notification_settings_user_id'), table_name='user_notification_settings')
    op.drop_index(op.f('ix_user_notification_settings_id'), table_name='user_notification_settings')
    op.create_unique_constraint('user_notification_settings_user_id_key', 'user_notification_settings', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_notification_settings_user_id', 'user_notification_settings', ['user_id'], unique=False)
    op.create_index('idx_notification_settings_enabled_time', 'user_notification_settings', ['is_enabled', 'notification_time_utc'], unique=False, postgresql_where='(is_enabled = true)')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_id'), table_name='user_devices')
    op.create_index('idx_user_devices_user_id', 'user_devices', ['user_id'], unique=False)
    op.create_index('idx_user_devices_token', 'user_devices', ['fcm_token'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_user_devices_stale', 'user_devices', ['last_seen_at'], unique=False, postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_user_categories_user_id'), table_name='user_categories')
    op.create_index('idx_user_categories_user_id', 'user_categories', ['user_id'], unique=False)
    op.alter_column('user_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('spaces', sa.Column('ai_ready', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('spaces', sa.Column('member_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('spaces', sa.Column('is_pinned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('spaces', sa.Column('is_public', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_spaces_is_active'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_invite_token'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_created_by'), table_name='spaces')
    op.create_unique_constraint('spaces_invite_token_key', 'spaces', ['invite_token'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_spaces_is_public', 'spaces', ['is_public'], unique=False)
    op.create_index('idx_spaces_is_pinned', 'spaces', ['is_pinned'], unique=False)
    op.create_index('idx_spaces_is_active', 'spaces', ['is_active'], unique=False)
    op.create_index('idx_spaces_invite_token', 'spaces', ['invite_token'], unique=False)
    op.create_index('idx_spaces_created_by', 'spaces', ['created_by'], unique=False)
    op.create_index('idx_spaces_ai_ready', 'spaces', ['ai_ready'], unique=False)
    op.alter_column('spaces', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_space_members_user_id'), table_name='space_members')
    op.drop_index(op.f('ix_space_members_space_id'), table_name='space_members')
    op.drop_index(op.f('ix_space_members_role'), table_name='space_members')
    op.create_unique_constraint('uq_space_user', 'space_members', ['space_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_space_members_user_id', 'space_members', ['user_id'], unique=False)
    op.create_index('idx_space_members_space_id', 'space_members', ['space_id'], unique=False)
    op.create_index('idx_space_members_role', 'space_members', ['role'], unique=False)
    op.drop_index(op.f('ix_space_invitations_token'), table_name='space_invitations')
    op.drop_index(op.f('ix_space_invitations_space_id'), table_name='space_invitations')
    op.drop_index(op.f('ix_space_invitations_email'), table_name='space_invitations')
    op.create_unique_constraint('uq_space_invitation_email', 'space_invitations', ['space_id', 'email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('space_invitations_token_key', 'space_invitations', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_space_invitations_token', 'space_invitations', ['token'], unique=False)
    op.create_index('idx_space_invitations_space_id', 'space_invitations', ['space_id'], unique=False)
    op.create_index('idx_space_invitations_email', 'space_invitations', ['email'], unique=False)
    op.drop_index(op.f('ix_space_content_space_id'), table_name='space_content')
    op.drop_index(op.f('ix_space_content_content_id'), table_name='space_content')
    op.drop_index(op.f('ix_space_content_added_at'), table_name='space_content')
    op.create_unique_constraint('uq_space_content', 'space_content', ['space_id', 'content_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_space_content_space_id', 'space_content', ['space_id'], unique=False)
    op.create_index('idx_space_content_content_id', 'space_content', ['content_id'], unique=False)
    op.create_index('idx_space_content_added_at', 'space_content', ['added_at'], unique=False)
    op.drop_index(op.f('ix_notification_history_user_id'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_id'), table_name='notification_history')
    op.drop_index(op.f('ix_notification_history_content_item_id'), table_name='notification_history')
    op.create_index('unique_daily_notification', 'notification_history', ['user_id', 'content_item_id', sa.text('date(sent_at)')], unique=True)
    op.create_index('idx_notification_history_user_date', 'notification_history', ['user_id', sa.text('sent_at DESC')], unique=False)
    op.create_index('idx_notification_history_content', 'notification_history', ['content_item_id'], unique=False)
    # Use raw SQL with IF EXISTS for failsafe downgrade
    op.execute("DROP INDEX IF EXISTS ix_magic_link_tokens_token")
    op.create_index('ix_magic_link_tokens_token', 'magic_link_tokens', ['token'], unique=False)
    # Create constraint only if it doesn't exist - use DO block for conditional logic
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'uq_magic_link_tokens_token') THEN
                ALTER TABLE magic_link_tokens ADD CONSTRAINT uq_magic_link_tokens_token UNIQUE (token);
            END IF;
        END $$;
    """)
    op.drop_index(op.f('ix_content_items_user_category_id'), table_name='content_items')
    op.create_index('idx_content_items_user_category_id', 'content_items', ['user_category_id'], unique=False)
    op.alter_column('content_items', 'processing_status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='processingstatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'::processingstatus"))
    op.alter_column('content_items', 'ai_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('content_items', 'ingestion_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # Commented out in upgrade, so also comment out in downgrade
    # op.alter_column('content_items', 'key_takeaways',
    #            existing_type=sa.ARRAY(sa.Text()),
    #            type_=postgresql.JSONB(astext_type=sa.Text()),
    #            existing_nullable=True)
    # Use IF EXISTS for failsafe column drops
    op.execute("ALTER TABLE content_items DROP COLUMN IF EXISTS source_app_package")
    op.execute("ALTER TABLE content_items DROP COLUMN IF EXISTS source_app_name")
    op.create_table('search_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='search_history_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='search_history_pkey')
    )
    op.create_index('idx_search_history_user_id', 'search_history', ['user_id'], unique=False)
    op.create_index('idx_search_history_created_at', 'search_history', ['created_at'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('summary_style', sa.VARCHAR(length=50), server_default=sa.text("'bullet_points'::character varying"), autoincrement=False, nullable=False),
    sa.Column('auto_categorize', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('connected_sources', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('daily_gems_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('daily_gems_time', sa.VARCHAR(length=20), server_default=sa.text("'9:00 AM'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_preferences_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_preferences_pkey'),
    sa.UniqueConstraint('user_id', name='user_preferences_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_user_preferences_user_id', 'user_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###
