"""Create content_items table

Revision ID: dbd94275e9bb
Revises: a0b4f24a7042
Create Date: 2025-12-22 09:31:59.154668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd94275e9bb'
down_revision: Union[str, None] = 'a0b4f24a7042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('source_app', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_category'), 'content_items', ['category'], unique=False)
    op.create_index(op.f('ix_content_items_created_at'), 'content_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_items_is_done'), 'content_items', ['is_done'], unique=False)
    op.create_index(op.f('ix_content_items_is_favorite'), 'content_items', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_content_items_source_app'), 'content_items', ['source_app'], unique=False)
    op.create_index(op.f('ix_content_items_user_id'), 'content_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_items_user_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_source_app'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_is_favorite'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_is_done'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_created_at'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_category'), table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###
